version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.5.0
    working_directory: ~/exclonidraw

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci

  typecheck:
    executor: node-executor
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Run TypeScript type check
          command: npx tsc --noEmit

  lint:
    executor: node-executor
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Run linter
          command: npm run lint

  build:
    executor: node-executor
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Build React app
          command: npm run build
      - run:
          name: Electron build (optional)
          command: |
            if [ -f "electron-builder.yml" ]; then
              npx electron-builder --dir
            else
              echo "Skipping electron build (no config)"
            fi

workflows:
  version: 2
  build-and-test:
    jobs:
      - install
      - typecheck:
          requires:
            - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - typecheck
            - lint
